
// import type { Place } from '../types';

// export const places: Place[] = [
//   {
//     id: 1,
//     name: "Dassam Falls",
//     coords: [23.1895, 85.4572],
//     images: ["https://picsum.photos/seed/dassam/400/300"],
//     description: "A natural cascade across the Kanchi River, a tributary of the Subarnarekha River. The water falls from a height of 44 metres (144 ft).",
//     category: "popular",
//   },
//   {
//     id: 2,
//     name: "Betla National Park",
//     coords: [23.8893, 84.1925],
//     images: ["https://picsum.photos/seed/betla/400/300"],
//     description: "A beautiful national park which is home to a wide variety of wildlife, including tigers, elephants, and deer. It's a paradise for nature lovers.",
//     category: "popular",
//   },
//   {
//     id: 3,
//     name: "Patratu Valley",
//     coords: [23.6664, 85.2891],
//     images: ["https://picsum.photos/seed/patratu/400/300"],
//     description: "Known for its stunning winding roads and lush green landscapes, offering breathtaking panoramic views, especially during sunrise and sunset.",
//     category: "popular",
//   },
//   {
//     id: 4,
//     name: "Tribal Research Institute Museum",
//     coords: [23.3855, 85.3364],
//     images: ["https://picsum.photos/seed/tribal/400/300"],
//     description: "Showcases the rich culture and heritage of the various tribal communities of Jharkhand through its exhibits of artifacts, costumes, and dioramas.",
//     category: "tribal",
//   },
//   {
//     id: 5,
//     name: "Hundru Falls",
//     coords: [23.4542, 85.6542],
//     images: ["https://picsum.photos/seed/hundru/400/300"],
//     description: "One of the highest waterfalls in the state, where the Subarnarekha River falls from a height of 98 metres (322 ft), creating a magnificent sight.",
//     category: "popular",
//   },
//   {
//     id: 6,
//     name: "Netarhat (Queen of Chotanagpur)",
//     coords: [23.4833, 84.2667],
//     images: ["https://picsum.photos/seed/netarhat/400/300"],
//     description: "A serene hill station known for its glorious sunrises and sunsets. It has a unique culture influenced by local tribes.",
//     category: "tribal",
//   }
// ];


import type { Place } from '../types';

export const places: Place[] = [
  {
    id: 1,
    name: "Dassam Falls",
    coords: [23.1895, 85.4572],
    images: ["https://picsum.photos/seed/dassam/400/300"],
    description: "A natural cascade across the Kanchi River, a tributary of the Subarnarekha River. The water falls from a height of 44 metres (144 ft).",
    category: "popular",
  },
  {
    id: 2,
    name: "Betla National Park",
    coords: [23.8893, 84.1925],
    images: ["https://picsum.photos/seed/betla/400/300"],
    description: "A beautiful national park which is home to a wide variety of wildlife, including tigers, elephants, and deer. It's a paradise for nature lovers.",
    category: "popular",
  },
  {
    id: 3,
    name: "Patratu Valley",
    coords: [23.6664, 85.2891],
    images: ["https://picsum.photos/seed/patratu/400/300"],
    description: "Known for its stunning winding roads and lush green landscapes, offering breathtaking panoramic views, especially during sunrise and sunset.",
    category: "popular",
  },
  {
    id: 4,
    name: "Tribal Research Institute Museum",
    coords: [23.3855, 85.3364],
    images: ["https://picsum.photos/seed/tribal/400/300"],
    description: "Showcases the rich culture and heritage of the various tribal communities of Jharkhand through its exhibits of artifacts, costumes, and dioramas.",
    category: "tribal",
  },
  {
    id: 5,
    name: "Hundru Falls",
    coords: [23.4542, 85.6542],
    images: ["https://picsum.photos/seed/hundru/400/300"],
    description: "One of the highest waterfalls in the state, where the Subarnarekha River falls from a height of 98 metres (322 ft), creating a magnificent sight.",
    category: "popular",
  },
  {
    id: 6,
    name: "Netarhat (Queen of Chotanagpur)",
    coords: [23.4833, 84.2667],
    images: ["https://picsum.photos/seed/netarhat/400/300"],
    description: "A serene hill station known for its glorious sunrises and sunsets. It has a unique culture influenced by local tribes.",
    category: "tribal",
  },
  {
    id: 7,
    name: "Jonha Falls",
    coords: [23.3203, 85.5619],
    images: ["https://picsum.photos/seed/jonha/400/300"],
    description: "Also known as Gautamdhara Falls, this waterfall drops from 43 meters and is surrounded by scenic beauty and tribal villages.",
    category: "popular",
  },
  {
    id: 8,
    name: "Pahari Mandir",
    coords: [23.3719, 85.3250],
    images: ["https://picsum.photos/seed/pahari/400/300"],
    description: "A historic temple dedicated to Lord Shiva situated on a hilltop in Ranchi, offering panoramic views of the city.",
    category: "popular",
  },
  {
    id: 9,
    name: "Jagannath Temple Ranchi",
    coords: [23.3436, 85.2667],
    images: ["https://picsum.photos/seed/jagannath/400/300"],
    description: "A 17th-century temple resembling the famous Jagannath Temple of Puri, known for its Rath Yatra festival.",
    category: "popular",
  },
  {
    id: 10,
    name: "Sun Temple, Bundu",
    coords: [23.1760, 85.7470],
    images: ["https://picsum.photos/seed/suntemple/400/300"],
    description: "A beautifully crafted temple dedicated to the Sun God, built in the shape of a massive chariot with 18 wheels and 7 horses.",
    category: "popular",
  },
  {
    id: 11,
    name: "Rock Garden Ranchi",
    coords: [23.3815, 85.3096],
    images: ["https://picsum.photos/seed/rockgarden/400/300"],
    description: "A scenic park built out of rocks, featuring statues, swings, and a beautiful view of the Kanke Dam.",
    category: "popular",
  },
  {
    id: 12,
    name: "Kanke Dam",
    coords: [23.3975, 85.2970],
    images: ["https://picsum.photos/seed/kanke/400/300"],
    description: "A serene reservoir surrounded by hills, popular for boating and evening walks.",
    category: "popular",
  },
  {
    id: 13,
    name: "Birsa Zoological Park",
    coords: [23.3741, 85.3228],
    images: ["https://picsum.photos/seed/birsa/400/300"],
    description: "A large zoo near Ranchi housing a wide variety of animals and birds in a natural environment.",
    category: "popular",
  },
  {
    id: 14,
    name: "Tagore Hill",
    coords: [23.4002, 85.3347],
    images: ["https://picsum.photos/seed/tagorehill/400/300"],
    description: "A popular tourist spot associated with Rabindranath Tagore, offering scenic views of Ranchi city.",
    category: "popular",
  },
  {
    id: 15,
    name: "Nakshatra Van",
    coords: [23.3606, 85.3220],
    images: ["https://picsum.photos/seed/nakshatra/400/300"],
    description: "An astronomical-themed park where plants are arranged according to the 27 Nakshatras of Hindu astrology.",
    category: "popular",
  },
  {
    id: 16,
    name: "Rajrappa Temple",
    coords: [23.6301, 85.6931],
    images: ["https://picsum.photos/seed/rajrappa/400/300"],
    description: "A famous Shakti shrine dedicated to Goddess Chhinnamasta, situated at the confluence of the Damodar and Bhairavi rivers.",
    category: "tribal",
  },
  {
    id: 17,
    name: "Itkhori Temple",
    coords: [24.0167, 85.0500],
    images: ["https://picsum.photos/seed/itkhori/400/300"],
    description: "A spiritual site associated with Buddhism, Jainism, and Hinduism, making it a unique confluence of religions.",
    category: "tribal",
  },
  {
    id: 18,
    name: "Shikharji (Parasnath Hills)",
    coords: [24.2500, 86.2833],
    images: ["https://picsum.photos/seed/parasnath/400/300"],
    description: "One of the most important Jain pilgrimage sites, located on the highest hill of Jharkhand.",
    category: "tribal",
  },
  {
    id: 19,
    name: "Hazaribagh Lake",
    coords: [23.9966, 85.3616],
    images: ["https://picsum.photos/seed/hazaribagh/400/300"],
    description: "A peaceful artificial lake built during the British era, surrounded by greenery and perfect for picnics.",
    category: "popular",
  },
  {
    id: 20,
    name: "Maithon Dam",
    coords: [23.8000, 86.8333],
    images: ["https://picsum.photos/seed/maithon/400/300"],
    description: "A major dam on the Barakar River, known as the 'Lake of Damodar Valley', offering boating and water sports.",
    category: "popular",
  },
  {
    id: 21,
    name: "Tilaiya Dam",
    coords: [24.4167, 85.4833],
    images: ["https://picsum.photos/seed/tilaiya/400/300"],
    description: "The first dam built by Damodar Valley Corporation, surrounded by beautiful hills and forests.",
    category: "popular",
  },
  {
    id: 22,
    name: "Topchanchi Lake",
    coords: [23.9000, 86.2167],
    images: ["https://picsum.photos/seed/topchanchi/400/300"],
    description: "A picturesque lake surrounded by lush greenery, ideal for birdwatching and boating.",
    category: "popular",
  },
  {
    id: 23,
    name: "Ghaghri Falls",
    coords: [23.4667, 84.2667],
    images: ["https://picsum.photos/seed/ghaghri/400/300"],
    description: "A scenic waterfall near Netarhat, hidden within dense forests and popular among trekkers.",
    category: "popular",
  },
  {
    id: 24,
    name: "Palamau Fort",
    coords: [23.8833, 84.0833],
    images: ["https://picsum.photos/seed/palamaufort/400/300"],
    description: "An ancient fort built in the 17th century by the Chero kings, located inside Betla National Park.",
    category: "tribal",
  },
  {
    id: 25,
    name: "Lodh Falls",
    coords: [23.6000, 84.6333],
    images: ["https://picsum.photos/seed/lodh/400/300"],
    description: "The highest waterfall in Jharkhand, falling from 143 meters, located deep in the forests of Latehar.",
    category: "popular",
  },
  {
    id: 26,
    name: "Baidyanath Jyotirlinga, Deoghar",
    coords: [24.4833, 86.7000],
    images: ["https://picsum.photos/seed/deoghar/400/300"],
    description: "One of the 12 Jyotirlingas dedicated to Lord Shiva, a major pilgrimage destination visited by millions every year.",
    category: "popular",
  },
  {
    id: 27,
    name: "Basukinath Temple",
    coords: [24.5000, 87.0500],
    images: ["https://picsum.photos/seed/basukinath/400/300"],
    description: "A prominent Shiva temple, considered as a twin shrine of Baidyanath Jyotirlinga.",
    category: "popular",
  },
  {
    id: 28,
    name: "Maluti Temples",
    coords: [24.3333, 87.3333],
    images: ["https://picsum.photos/seed/maluti/400/300"],
    description: "A cluster of terracotta temples built in the 17th century, showcasing Bengal-style temple architecture.",
    category: "tribal",
  },
  {
    id: 29,
    name: "Khandoli Park",
    coords: [23.8500, 86.1667],
    images: ["https://picsum.photos/seed/khandoli/400/300"],
    description: "An adventure park with boating, trekking, and water sports facilities built around Khandoli Dam.",
    category: "popular",
  },
  {
    id: 30,
    name: "Khandoli Hill",
    coords: [23.8400, 86.1500],
    images: ["https://picsum.photos/seed/khandolihill/400/300"],
    description: "A rocky hill near Giridih, popular for rock climbing, paragliding, and panoramic views.",
    category: "popular",
  },
  {
    id: 31,
    name: "Usri Falls",
    coords: [24.2833, 86.3000],
    images: ["https://picsum.photos/seed/usri/400/300"],
    description: "A scenic three-tiered waterfall located near Giridih, popular for picnics and photography.",
    category: "popular",
  },
  {
    id: 32,
    name: "Harihar Dham",
    coords: [24.2500, 86.2167],
    images: ["https://picsum.photos/seed/harihardham/400/300"],
    description: "Home to one of the largest Shiva lingams in India, attracting thousands of devotees.",
    category: "popular",
  },
  {
    id: 33,
    name: "Bokaro Steel Plant",
    coords: [23.6333, 86.1500],
    images: ["https://picsum.photos/seed/bokaro/400/300"],
    description: "Asia’s largest steel plant township, symbolizing industrial progress and modern urban planning.",
    category: "popular",
  },
  {
    id: 34,
    name: "Garga Dam",
    coords: [23.6167, 86.2167],
    images: ["https://picsum.photos/seed/garga/400/300"],
    description: "A peaceful picnic spot with boating facilities near Bokaro city.",
    category: "popular",
  },
  {
    id: 35,
    name: "Tenughat Dam",
    coords: [23.7500, 85.7500],
    images: ["https://picsum.photos/seed/tenughat/400/300"],
    description: "A long dam on the Damodar River, offering stunning sunset views and fishing opportunities.",
    category: "popular",
  },
  {
    id: 36,
    name: "Panch Ghagh Falls",
    coords: [23.3167, 85.4167],
    images: ["https://picsum.photos/seed/panchghagh/400/300"],
    description: "A collection of five waterfalls near Khunti, surrounded by scenic landscapes.",
    category: "popular",
  },
  {
    id: 37,
    name: "Angrabadi Temple Complex",
    coords: [23.2833, 85.2833],
    images: ["https://picsum.photos/seed/angrabadi/400/300"],
    description: "A temple complex with shrines dedicated to Lord Ganesh, Hanuman, and Ram-Sita.",
    category: "tribal",
  },
  {
    id: 38,
    name: "Bhadrakali Temple, Itkhori",
    coords: [24.0333, 85.0667],
    images: ["https://picsum.photos/seed/bhadrakali/400/300"],
    description: "A revered temple dedicated to Goddess Bhadrakali, located near the confluence of two rivers.",
    category: "tribal",
  },
  {
    id: 39,
    name: "Noori Masjid, Hazaribagh",
    coords: [24.0000, 85.3667],
    images: ["https://picsum.photos/seed/noorimasjid/400/300"],
    description: "A historic mosque in Hazaribagh town, known for its peaceful surroundings.",
    category: "popular",
  },
  {
    id: 40,
    name: "Ramgarh Cantonment",
    coords: [23.6333, 85.5167],
    images: ["https://picsum.photos/seed/ramgarh/400/300"],
    description: "A historic military base that played an important role during World War II.",
    category: "popular",
  },
  {
    id: 41,
    name: "Chandrapura Thermal Power Station",
    coords: [23.7500, 86.1167],
    images: ["https://picsum.photos/seed/chandrapura/400/300"],
    description: "One of the oldest coal-based thermal power stations in India.",
    category: "popular",
  },
  {
    id: 42,
    name: "Panchet Dam",
    coords: [23.6500, 86.7000],
    images: ["https://picsum.photos/seed/panchet/400/300"],
    description: "A dam built on the Damodar River, offering scenic beauty and fishing opportunities.",
    category: "popular",
  },
  {
    id: 43,
    name: "Damodar Valley Corporation",
    coords: [23.6667, 86.1500],
    images: ["https://picsum.photos/seed/dvc/400/300"],
    description: "One of India’s first multipurpose river valley projects, crucial for Jharkhand’s industrial growth.",
    category: "popular",
  },
  {
    id: 44,
    name: "Patratu Dam",
    coords: [23.6667, 85.2833],
    images: ["https://picsum.photos/seed/patratudam/400/300"],
    description: "A dam surrounded by hills and forests, famous for its sunrise and boating.",
    category: "popular",
  },
  {
    id: 45,
    name: "Sita Falls",
    coords: [23.4167, 85.5667],
    images: ["https://picsum.photos/seed/sita/400/300"],
    description: "A charming waterfall near Ranchi named after Goddess Sita, with crystal clear waters.",
    category: "popular",
  },
  {
    id: 46,
    name: "Anjan Dham",
    coords: [23.8167, 85.5000],
    images: ["https://picsum.photos/seed/anjan/400/300"],
    description: "A pilgrimage site believed to be the birthplace of Lord Hanuman, located in Gumla district.",
    category: "tribal",
  },
  {
    id: 47,
    name: "Neterhat Dam",
    coords: [23.4667, 84.2833],
    images: ["https://picsum.photos/seed/neterhatdam/400/300"],
    description: "A peaceful spot in the Netarhat plateau with boating facilities amidst nature.",
    category: "popular",
  },
    {
    id: 48,
    name: "Hirni Falls",
    coords: [22.9333, 85.2167],
    images: ["https://picsum.photos/seed/hirni/400/300"],
    description: "A scenic waterfall located near Ranchi, surrounded by dense forests and tribal villages.",
    category: "popular",
  },
  {
    id: 49,
    name: "Rajmahal Hills",
    coords: [25.0333, 87.6333],
    images: ["https://picsum.photos/seed/rajmahal/400/300"],
    description: "Geologically significant hills formed from ancient volcanic rocks, also rich in fossils.",
    category: "tribal",
  },
  {
    id: 50,
    name: "Udhwa Bird Sanctuary",
    coords: [24.8833, 87.8167],
    images: ["https://picsum.photos/seed/udhwa/400/300"],
    description: "The only bird sanctuary in Jharkhand, spread across two lakes and home to migratory birds.",
    category: "popular",
  },
  {
    id: 51,
    name: "Tattapani Hot Springs",
    coords: [23.6167, 84.8667],
    images: ["https://picsum.photos/seed/tattapani/400/300"],
    description: "A natural hot water spring believed to have medicinal properties, located near Latehar.",
    category: "tribal",
  },
  {
    id: 52,
    name: "Palamau Tiger Reserve",
    coords: [23.8333, 84.0833],
    images: ["https://picsum.photos/seed/palamautiger/400/300"],
    description: "One of India’s first tiger reserves, rich in wildlife and part of Betla National Park.",
    category: "popular",
  },
  {
    id: 53,
    name: "Madhuban, Giridih",
    coords: [24.2500, 86.2833],
    images: ["https://picsum.photos/seed/madhuban/400/300"],
    description: "A major Jain pilgrimage site at the base of Parasnath Hills with several ancient temples.",
    category: "tribal",
  },
  {
    id: 54,
    name: "Kanti Waterfalls",
    coords: [23.4000, 85.5500],
    images: ["https://picsum.photos/seed/kanti/400/300"],
    description: "A lesser-known waterfall near Ranchi, popular for trekking and nature photography.",
    category: "popular",
  },
  {
    id: 55,
    name: "Lawapani Waterfalls",
    coords: [23.4667, 84.3000],
    images: ["https://picsum.photos/seed/lawapani/400/300"],
    description: "A hidden gem in the forests of Netarhat, offering a peaceful natural retreat.",
    category: "popular",
  },
  {
    id: 56,
    name: "Getalsud Dam",
    coords: [23.3833, 85.5667],
    images: ["https://picsum.photos/seed/getalsud/400/300"],
    description: "A large dam on the Subarnarekha River, popular for water sports and boating.",
    category: "popular",
  },
  {
    id: 57,
    name: "Hussainabad (Japla)",
    coords: [24.2833, 84.0500],
    images: ["https://picsum.photos/seed/japla/400/300"],
    description: "Known for historical ruins, temples, and the scenic beauty of the Son River valley.",
    category: "tribal",
  },
  {
    id: 58,
    name: "Chouparan Hills",
    coords: [24.1833, 85.2833],
    images: ["https://picsum.photos/seed/chouparan/400/300"],
    description: "A beautiful hilly region in Hazaribagh district, dotted with forests and streams.",
    category: "popular",
  },
  {
    id: 59,
    name: "Sikidiri Hydel Power Station",
    coords: [23.4000, 85.5167],
    images: ["https://picsum.photos/seed/sikidiri/400/300"],
    description: "A scenic spot near Ranchi, combining hydroelectric power facilities with waterfalls.",
    category: "popular",
  },
  {
    id: 60,
    name: "Surya Mandir, Ranchi",
    coords: [23.3500, 85.3333],
    images: ["https://picsum.photos/seed/suryamandir/400/300"],
    description: "A beautiful Sun temple with intricate architecture and cultural significance.",
    category: "popular",
  }
];

